repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.1
    hooks:
      # Run the linter
      - id: ruff-check
        args: ["--fix", "--exit-non-zero-on-fix"]
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v22.1.8
    hooks:
    -   id: clang-format
        types_or: [c++, c]

  - repo: https://gitlab.com/daverona/pre-commit/cpp
    rev: 0.8.0
    hooks:
    -   id: cpplint
        # Don't want to fix thirdparty ...
        exclude: ^(include/liboculus/thirdparty)/.*
        # - runtime/int is warning to use int32_t instead of "long int"
        #   didn't feel like fixing it.
        #
        # - readability/todo enforces that todos should have username.
        #
        # - whitespace/indent_namespace, whitespace/indent, whitespace/comments
        #   and build/include_order conflict with choices made by clang format
        args: ["--quiet", "--filter=-runtime/int,-readability/todo,-whitespace/indent_namespace,-whitespace/indent,-whitespace/comments,-build/include_order"]

  # CMake formatter
  # - repo: https://github.com/BlankSpruce/gersemi
  #   rev: 0.19.3
  #   hooks:
  #   - id: gersemi

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
