name: CMake build CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  cmake:
    name: Build with CMake
    runs-on: ubuntu-24.04

    steps:
      - name: Install dependencies with awalsh128/cache-apt-pkgs-action
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: \
            libasio-dev \
            libboost-system-dev \
            libfmt-dev
            libspdlog-dev \
          version: 1.0

      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Build Project
        uses: threeal/cmake-action@v2.1.0
